apiVersion: apps/v1
kind: Deployment
metadata:
  name: Menu
  labels:
    app: Menu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Menu
  template:
    metadata:
      labels:
        app: Menu
    spec:
      containers:
        - name: Menu
          image: username/Menu:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5